#ifndef SF3CONFIG_LOCALIZATION_H
#define SF3CONFIG_LOCALIZATION_H

typedef enum AppLanguage {
    APP_LANGUAGE_EN_US,
    APP_LANGUAGE_PT_BR,
    APP_LANGUAGE_COUNT,
} AppLanguage;

typedef enum TextId {
    TEXT_APP_NAME,
    TEXT_TITLE,
    TEXT_APPLY_NEXT_START,
    TEXT_INPUT_HELP,
    TEXT_FULLSCREEN,
    TEXT_WINDOW_WIDTH,
    TEXT_WINDOW_HEIGHT,
    TEXT_SCALE_MODE,
    TEXT_BEZEL,
    TEXT_SCANLINES,
    TEXT_SCANLINE_OPACITY,
    TEXT_PLAYERS_ABOVE_HUD,
    TEXT_SAVE,
    TEXT_DEFAULTS,
    TEXT_CANCEL,
    TEXT_STATUS_DIRTY,
    TEXT_STATUS_LOADED,
    TEXT_STATUS_SAVED,
    TEXT_STATUS_SAVE_FAILED,
    TEXT_STATUS_LANGUAGE_CHANGED,
    TEXT_UNSAVED_TITLE,
    TEXT_UNSAVED_MESSAGE,
    TEXT_CONTINUE_EDITING,
    TEXT_DISCARD,
    TEXT_SAVE_ERROR_TITLE,
    TEXT_FILE_PREFIX,
    TEXT_ERR_LOCATE_APP_FOLDER,
    TEXT_ERR_CREATE_CONFIG_PATH,
    TEXT_ERR_ACCESS_FOLDER,
    TEXT_ERR_CREATE_CONFIG_FILE_PATH,
    TEXT_ERR_INVALID_READ_PARAMS,
    TEXT_ERR_OPEN_FILE,
    TEXT_ERR_READ_FILE,
    TEXT_ERR_INVALID_WRITE_PARAMS,
    TEXT_ERR_READ_FOR_SAVE,
    TEXT_ERR_CREATE_TEMP_PATH,
    TEXT_ERR_WRITE_FILE,
    TEXT_ERR_FINISH_WRITE,
    TEXT_ERR_REPLACE_FILE,
    TEXT_CONFIG_HEADER,
    TEXT_COUNT,
} TextId;

void Localization_Init(void);
void Localization_SetLanguage(AppLanguage language);
AppLanguage Localization_GetLanguage(void);
const char* Localize(TextId text);

#endif
